$schema: http://json-schema.org/draft-04/hyper-schema
title: Local config
type: object
required:
  - agent
  - postgres
properties:
  controller:
    type: string
    enum:
      - mastodon
      - misskey
      - dolphin
      - pleroma
  environment:
    type: string
    enum:
      - development
      - production
  agent:
    type: object
    required:
      - test
      - info
    properties:
      test:
        type: object
        required:
          - token
        properties:
          token:
            type: string
      info:
        type: object
        required:
          - token
        properties:
          token:
            type: string
  tagging:
    type: object
    properties:
      dictionaries:
        type: array
        items:
          type: object
          required:
            - url
          properties:
            url:
              type: string
              format: uri
            type:
              type: string
              enum:
                - multi_field
                - relative
                - mecab
      attachment_tags:
        type: object
        properties:
          image:
            type:
              - string
              - 'null'
          video:
            type:
              - string
              - 'null'
          audio:
            type:
              - string
              - 'null'
      default_tags:
        type: array
        items:
          type: string
  slack:
    type: object
    required:
      - hooks
    properties:
      hooks:
        type: array
        items:
          type: string
          format: uri
  postgres:
    type: object
    required:
      - dsn
    properties:
      dsn:
        type: string
        format: uri
  twitter:
    type: object
    required:
      - consumer
    properties:
      consumer:
        type: object
        required:
          - key
          - secret
        properties:
          key:
            type: string
          secret:
            type: string
      status:
        type: object
        properties:
          tags:
            type: array
            items:
              type: string
  amazon:
    type: object
    required:
      - associate_tag
      - access_key
      - secret_key
    properties:
      associate_tag:
        type: string
      access_key:
        type: string
      secret_key:
        type: string
      affiliate:
        type: boolean
  spotify:
    type: object
    required:
      - client_id
      - client_secret
    properties:
      client_id:
        type: string
      client_secret:
        type: string
  google:
    type: object
    required:
      - api
    properties:
      api:
        type: object
        required:
          - key
        properties:
          key:
            type: string
  programs:
    type: object
    required:
      - url
    properties:
      url:
        type: string
        format: uri
  webui:
    type: object
    properties:
      livecure:
        type: boolean
  sidekiq:
    type: object
    properties:
      concurrency:
        type: integer
      redis:
        type: object
        required:
          - url
        properties:
          url:
            type: string
            format: uri
      auth:
        type: object
        required:
          - password
        properties:
          user:
            type: string
          password:
            type: string
      schedule:
        type: object
        properties: {}
  puma:
    type: object
    properties:
      port:
        type: integer
  crypt:
    type: object
    properties:
      salt:
        type: string
      password:
        type: string
