meisskey:
  type: object
  required:
    - url
  properties:
    url:
      type: string
      format: uri
    status:
      type: object
      properties:
        max_length:
          type: integer
