package:
  version: 3.2.1
  url: https://github.com/pooza/mulukhiya-toot-proxy
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
controller: mastodon
handler:
  mastodon:
    pre_toot:
      - user_config_command
      - filter_command
      - growi_clipping_command
      - dropbox_clipping_command
      - shortened_url
      - url_normalize
      - itunes_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - itunes_nowplaying
      - spotify_nowplaying
      - amazon_nowplaying
      - canonical_url
      - amazon_url
      - itunes_url
      - itunes_image
      - spotify_image
      - amazon_image
      - tagging
    post_toot:
      - growi_clipping_command
      - dropbox_clipping_command
      - admin_notification
      - mention_notification
      - result_notification
    pre_webhook:
      - shortened_url
      - url_normalize
      - itunes_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - itunes_nowplaying
      - spotify_nowplaying
      - amazon_nowplaying
      - canonical_url
      - amazon_url
      - itunes_url
      - itunes_image
      - spotify_image
      - amazon_image
      - webhook_image
      - tagging
    post_webhook:
      - admin_notification
      - mention_notification
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_fav:
      - fav_dropbox_clipping
      - fav_growi_clipping
      - fav_notification
      - result_notification
    post_boost:
      - boost_notification
      - result_notification
    post_search:
      - result_notification
  dolphin:
    pre_toot:
      - user_config_command
      - shortened_url
      - url_normalize
      - itunes_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - itunes_nowplaying
      - spotify_nowplaying
      - amazon_nowplaying
      - canonical_url
      - amazon_url
      - itunes_url
      - tagging
    post_toot:
      - result_notification
  default:
    timeout: 10
  mention_notification:
    disable: true
  fav_notification:
    disable: true
  boost_notification:
    disable: true
  fav_growi_clipping:
    disable: true
  fav_dropbox_clipping:
    disable: true
  image_resize:
    pixel: 1280
  amazon_image:
    timeout: 20
worker:
  media_cleaning:
    days: 1
shortened_url:
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
    - spoti.fi
    - apple.co
test:
  excludes:
    ci:
      - clipping_worker
      - dolphin_controller
      - dropbox_clipper
      - growi_clipper
      - handler
      - mastodon_controller
      - tagging_dictionary
    no_db:
      - account
      - mastodon_uri
      - note
      - query_template
      - toot
      - webhook
    no_amazon:
      - amazon_service
    no_spotify:
      - spotify_service
      - spotify_uri
    dolphin:
      - clipping_worker
      - mastodon_controller
      - mastodon_uri
      - toot
    mastodon:
      - dolphin_controller
      - dolphin_uri
      - note
mastodon:
  url: https://mstdn.example.com/
  oauth:
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    scopes:
      - write:statuses
      - write:media
  patterns:
    - pattern: ^/web/statuses/([[:digit:]]+)
    - pattern: ^/@[[:word:]]+/([[:digit:]]+)
    - pattern: ^/users/[[:word:]]+/statuses/([[:digit:]]+)
  toot: &mastodon_toot
    field: status
    label: トゥート
    max_length: 500
    visibility_name:
      direct: direct
  message: *mastodon_toot
  search:
    limit: 40
  hashtag:
    pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
  account:
    pattern: (@[_0-9a-zA-Z]+(@[-.0-9a-zA-Z]+)?)
dolphin:
  url: https://dol.example.com/
  note: &dolphin_note
    field: text
    label: ノート
    max_length: 500
    visibility_name:
      direct: specified
  message: *dolphin_note
amazon:
  country: jp
  urls:
    jp: https://www.amazon.co.jp/
  retry_limit: 5
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
  affiliate: false
spotify:
  language: ja,en-US;q=0.9,en;q=0.8
  retry_limit: 5
  urls:
    track: https://open.spotify.com/
  patterns:
    - pattern: /track/([[:alnum:]]+)
itunes:
  country: jp
  lang: ja_jp
  urls:
    search: https://itunes.apple.com/search
    lookup: https://itunes.apple.com/lookup
  patterns:
    - pattern: /album/.*?/?([[:digit:]]+)$
      shortenable: true
  hosts:
    - music.apple.com
    - itunes.apple.com
youtube:
  urls:
    videos: https://www.googleapis.com/youtube/v3/videos
twittodon:
  pattern: \n(\n\(?.*?via\.\s+[^)]*\)?)$
artist_parser:
  delimiters:
    - /
    - 、
  patterns:
    - pattern: ^[^():]+、
      delimited: true
    - pattern: '^(((歌|語り):)?.+\s*\(CV[.:]\s*.+\)、?){2,}$'
      delimited: true
    - pattern: '^(.+\s*\(.+\)、?){2,}$'
      delimited: true
    - pattern: '^((歌|語り):)?(.+)\s*\(CV[.:]\s*(.+)\)$'
      items:
        - drop: true
        - drop: true
        - split: true
        - strip: true
          split: true
          prefix: 'CV:'
    - pattern: '^歌:(.+)\s*コーラス:(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(コーラス:(.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(as\s*(.+)\)$'
      items:
        - strip: true
          prefix: 'CV:'
        - split: true
    - pattern: '^(.+)\s*\((.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
    - pattern: '^(.+)\s*feat\.\s*(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: feat.
user_config:
  redis:
    dsn: redis://localhost:6379/1
postgres:
  dsn: null
slack:
  hooks: []
sidekiq:
  redis:
    dsn: redis://localhost:6379/2
  auth:
    user: admin
    password: ''
tagging:
  word:
    minimum_length: 3
  attachment_tags:
    image: image
    video: video
    audio: audio
  ignore_addresses:
    - '@relayctl@hashtag-relay.dtp-mstdn.jp'
webhook:
  salt: mulukhiya
