package:
  version: 1.3.0rc1
  url: https://github.com/pooza/mulukhiya-toot-proxy
shortened_url:
  timeout: 5
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
amazon:
  country: jp
  url: https://www.amazon.co.jp/
  retry_limit: 5
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
spotify:
  retry_limit: 5
