package:
  version: 1.2.5
  url: https://github.com/pooza/mulukhiya-toot-proxy
shortened_url:
  timeout: 5
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
amazon_uri:
  patterns:
    - /dp/([[:alnum:]]+)
    - /gp/product/([[:alnum:]]+)
    - /exec/obidos/ASIN/([[:alnum:]]+)
    - /o/ASIN/([[:alnum:]]+)
amazon_ecs:
  retry_limit: 5
