package:
  version: 1.3.13
  url: https://github.com/pooza/mulukhiya-toot-proxy
shortened_url:
  timeout: 5
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
    - spoti.fi
    - apple.co
amazon:
  urls:
    jp: https://www.amazon.co.jp/
  retry_limit: 5
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
spotify:
  retry_limit: 5
  urls:
    track: https://open.spotify.com/
  patterns:
    - pattern: /track/([[:alnum:]]+)
itunes:
  urls:
    search: https://itunes.apple.com/search
    lookup: https://itunes.apple.com/lookup
  patterns:
    - pattern: ([[:digit:]]+)$
