package:
  version: 1.1.0
  url: https://github.com/pooza/mulukhiya-toot-proxy
shortened_url:
  timeout: 5
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
