package:
  version: 3.8.0
  url: https://github.com/pooza/mulukhiya-toot-proxy
  description: 投稿内容の更新等を行うプロキシ。通称「モロヘイヤ」。
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
controller: mastodon
environment: development
handler:
  default:
    timeout: 5
  image_resize:
    pixel: 1280
  itunes_image:
    pixel: 480
  spotify_image:
    disable: true
worker:
  media_cleaning:
    days: 1
shortened_url:
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
    - spoti.fi
    - apple.co
test:
  filters:
    - name: ci
      cases:
        - dolphin_controller
        - handler
        - mastodon_controller
        - slack
    - name: database
      cases:
        - account
        - clipping_worker
        - note_uri
        - query_template
        - status
        - toot_uri
        - user_config
    - name: amazon
      cases:
        - amazon_service
        - amazon_image_handler
        - amazon_nowplaying_handler
        - amazon_url_nowplaying_handler
    - name: spotify
      cases:
        - spotify_service
        - spotify_uri
        - spotify_image_handler
        - spotify_nowplaying_handler
        - spotify_url_nowplaying_handler
    - name: you_tube
      cases:
        - youtube_service
        - video_uri
        - youtube_image_handler
        - youtube_url_nowplaying_handler
    - name: dolphin
      cases:
        - mastodon_controller
        - misskey_controller
        - toot_uri
    - name: mastodon
      cases:
        - dolphin_controller
        - misskey_controller
        - note_uri
    - name: misskey
      cases:
        - mastodon_controller
        - dolphin_controller
        - toot_uri
    - name: dropbox
      cases:
        - dropbox_clipper
        - dropbox_bookmark_handler
        - dropbox_clipping_command_handler
    - name: growi
      cases:
        - growi_clipper
        - growi_bookmark_handler
        - growi_clipping_command_handler
    - name: webhook
      cases:
        - webhook
        - webhook_image_handler
webui:
  scripts:
    - https://cdn.jsdelivr.net/npm/vue/dist/vue.js
    - https://cdn.jsdelivr.net/npm/vue-select/dist/vue-select.min.js
    - https://cdn.jsdelivr.net/npm/vuejs-dialog/dist/vuejs-dialog.min.js
    - https://cdn.jsdelivr.net/npm/v-tooltip/dist/v-tooltip.min.js
    - https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js
    - https://cdn.jsdelivr.net/npm/js-yaml/dist/js-yaml.min.js
  stylesheets:
    - /mulukhiya/style/default
    - https://cdn.jsdelivr.net/npm/vue-select/dist/vue-select.css
    - https://cdn.jsdelivr.net/npm/vuejs-dialog/dist/vuejs-dialog.min.css
    - https://use.fontawesome.com/releases/v5.6.1/css/all.css
    - https://fonts.googleapis.com/css?family=Francois+One|Inconsolata&display=swap
  metadata:
    robots: noindex,nofollow
    viewport: width=800
  livecure: false
mastodon:
  url: https://mstdn.example.com/
  handlers:
    pre_toot:
      - user_config_command
      - filter_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - itunes_image
      - spotify_image
      - amazon_image
      - you_tube_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_toot:
      - user_config_command
      - filter_command
      - growi_clipping_command
      - dropbox_clipping_command
      - result_notification
    pre_webhook:
      - itunes_image
      - spotify_image
      - amazon_image
      - you_tube_image
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_fav:
      - result_notification
    post_boost:
      - result_notification
    post_search:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - post_fav
    - post_boost
    - post_search
    - post_bookmark
  oauth:
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    scopes:
      - write:statuses
      - write:media
      - read:filters
      - write:filters
  status:
    field: status
    key: id
    label: トゥート
    max_length: 500
    visibility_names:
      unlisted: unlisted
      private: private
      direct: direct
    patterns:
      - pattern: ^/web/statuses/([[:digit:]]+)
      - pattern: ^/@[[:word:]]+/([[:digit:]]+)
      - pattern: ^/users/[[:word:]]+/statuses/([[:digit:]]+)
  attachment:
    key: media_ids
  poll:
    options:
      field: options
  search:
    limit: 40
misskey:
  url: https://misskey.example.com/
  handlers:
    pre_toot:
      - user_config_command
      - mention_visibility
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_toot:
      - user_config_command
      - result_notification
    pre_webhook:
      - itunes_nowplaying
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  oauth:
    permission:
      - write:notes
      - write:drive
    callback_url: /mulukhiya/auth
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: text
    key: noteId
    label: ノート
    max_length: 500
    visibility_names:
      unlisted: home
      private: followers
      direct: specified
    patterns:
      - pattern: ^/notes/([[:alnum:]]+)
  attachment:
    key: fileIds
  poll:
    options:
      field: choices
dolphin:
  url: https://dolphin.example.com/
  handlers:
    pre_toot:
      - user_config_command
      - mention_visibility
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_toot:
      - user_config_command
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  events:
    - pre_toot
    - post_toot
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: text
    key: noteId
    label: ノート
    max_length: 500
    visibility_names:
      unlisted: home
      private: followers
      direct: specified
    patterns:
      - pattern: ^/notes/([[:alnum:]]+)
  attachment:
    key: fileIds
  poll:
    options:
      field: choices
amazon:
  marketplace: jp
  urls:
    jp: https://www.amazon.co.jp/
  retry_limit: 5
  resources:
    - Images.Primary.Small
    - Images.Primary.Medium
    - Images.Primary.Large
    - Images.Variants.Small
    - Images.Variants.Medium
    - Images.Variants.Large
    - ItemInfo.ByLineInfo
    - ItemInfo.ContentInfo
    - ItemInfo.ContentRating
    - ItemInfo.Classifications
    - ItemInfo.ExternalIds
    - ItemInfo.Features
    - ItemInfo.ManufactureInfo
    - ItemInfo.ProductInfo
    - ItemInfo.TechnicalInfo
    - ItemInfo.Title
    - ItemInfo.TradeInInfo
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
  affiliate: false
spotify:
  language: ja,en-US;q=0.9,en;q=0.8
  retry_limit: 5
  urls:
    track: https://open.spotify.com/
  patterns:
    - pattern: /track/([[:alnum:]]+)
itunes:
  country: jp
  lang: ja_jp
  urls:
    search: https://itunes.apple.com/search
    lookup: https://itunes.apple.com/lookup
  patterns:
    - pattern: /album/.*?/?([[:digit:]]+)$
      shortenable: true
  hosts:
    - music.apple.com
    - itunes.apple.com
youtube:
  url: https://www.googleapis.com/
twitter:
  consumer:
twittodon:
  pattern: \n(\n\(?.*?via\.\s+[^)]*\)?)$
artist_parser:
  delimiters:
    - /
    - 、
  patterns:
    - pattern: ^[^():]+、
      delimited: true
    - pattern: '^(((歌|語り):)?.+\s*\(CV[.:]\s*.+\)、?){2,}$'
      delimited: true
    - pattern: '^(.+\s*\(.+\)、?){2,}$'
      delimited: true
    - pattern: '^((歌|語り):)?(.+)\s*\(CV[.:]\s*(.+)\)$'
      items:
        - drop: true
        - drop: true
        - split: true
        - strip: true
          split: true
          prefix: 'CV:'
    - pattern: '^歌:(.+)\s*コーラス:(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(コーラス:(.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(as\s*(.+)\)$'
      items:
        - strip: true
          prefix: 'CV:'
        - split: true
    - pattern: '^(.+)\s*\((.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
    - pattern: '^(.+)\s*feat\.\s*(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: feat.
user_config:
  redis:
    dsn: redis://localhost:6379/1
postgres:
  dsn: null
slack:
  hooks: []
sidekiq:
  redis:
    dsn: redis://localhost:6379/2
  auth:
    user: admin
    password: ''
  concurrency: 5
  schedule:
    tagging_dictionary_update:
      every: 1d
      class: Mulukhiya::TaggingDictionaryUpdateWorker
    program_update:
      every: 1d
      class: Mulukhiya::ProgramUpdateWorker
    media_cleaning:
      every: 1d
      class: Mulukhiya::MediaCleaningWorker
    announcement:
      every: 2m
      class: Mulukhiya::AnnouncementWorker
puma:
  port: 3008
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
tagging:
  word:
    minimum_length: 3
  attachment_tags:
    image: image
    video: video
    audio: audio
  dictionaries:
    - url: https://script.google.com/macros/s/AKfycbwn4nqKhBwH3aDYd7bJ698-GWRJqpktpAdH11ramlBK87ym3ME/exec
      type: relative
    - url: https://script.google.com/macros/s/AKfycbzAUsRUuFLO72EgKta020v9OMtxvUtqUcPZNJ3_IMlOo8dRO7tW/exec
      type: relative
    - url: https://script.google.com/macros/s/AKfycbyy5EQHvhKfm1Lg6Ae4W7knG4BCSkvepJyB6MrzQ8UIxmFfZMJj/exec
      type: relative
agent:
  accts:
    - '@relayctl@hashtag-relay.dtp-mstdn.jp'
crypt:
  password: mulukhiya
  salt: mulukhiya
