package:
  version: 3.11.8
  url: https://github.com/pooza/mulukhiya-toot-proxy
  description: 投稿内容の更新等を行うプロキシ。通称「モロヘイヤ」。
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
controller: mastodon
environment: development
handler:
  default:
    timeout: 5
  image_resize:
    pixel: 1280
  image_format_convert:
    format: jpeg
  video_format_convert:
    timeout: 30
    format: mp4
  audio_format_convert:
    timeout: 10
    format: mp3
  itunes_image:
    pixel: 480
    timeout: 10
  amazon_image:
    timeout: 10
  spotify_image:
    timeout: 10
    disable: true
  tweet:
    disable: true
  shortened_url:
    domains:
      - t.co
      - goo.gl
      - bit.ly
      - ow.ly
      - amzn.to
      - amzn.asia
      - youtu.be
      - git.io
      - spoti.fi
      - apple.co
worker:
  media_cleaning:
    days: 1
  growi_clipping:
    federate: false
  dropbox_clipping:
    federate: true
parser:
  toot:
    patterns:
      - ^/web/statuses/([[:digit:]]+)
      - ^/@[[:word:]]+/([[:digit:]]+)
      - ^/users/[[:word:]]+/statuses/([[:digit:]]+)
      - ^/notice/([[:word:]]+)
    visibility:
      unlisted: unlisted
      private: private
      direct: direct
  note:
    patterns:
      - ^/notes/([[:alnum:]]+)
    visibility:
      unlisted: home
      private: followers
      direct: specified
test:
  filters:
    - name: ci
      cases:
        - mastodon_controller
        - handler
        - slack
        - account
        - access_token
        - status
        - user_config
        - tag_atom_feed_renderer
    - name: postgres
      cases:
        - clipping_worker
        - note_uri
        - query_template
        - toot_uri
    - name: mongo
      cases:
        - clipping_worker
        - note_uri
        - toot_uri
    - name: amazon
      cases:
        - amazon_service
        - amazon_image_handler
        - amazon_nowplaying_handler
        - amazon_url_nowplaying_handler
    - name: spotify
      cases:
        - spotify_service
        - spotify_uri
        - spotify_image_handler
        - spotify_nowplaying_handler
        - spotify_url_nowplaying_handler
    - name: you_tube
      cases:
        - youtube_service
        - video_uri
        - youtube_image_handler
        - youtube_url_nowplaying_handler
    - name: twitter
      cases:
        - twitter_service
        - tweet_handler
        - twitter_auth_contract
    - name: dolphin
      cases:
        - mastodon_controller
        - misskey_controller
        - meisskey_controller
        - pleroma_controller
        - mongo
        - access_token
        - mastodon_auth_contract
        - tag_atom_feed_renderer
    - name: mastodon
      cases:
        - dolphin_controller
        - misskey_controller
        - meisskey_controller
        - pleroma_controller
        - mongo
        - misskey_auth_contract
    - name: misskey
      cases:
        - mastodon_controller
        - meisskey_controller
        - dolphin_controller
        - pleroma_controller
        - mongo
        - mastodon_auth_contract
        - tag_atom_feed_renderer
    - name: meisskey
      cases:
        - mastodon_controller
        - misskey_controller
        - dolphin_controller
        - pleroma_controller
        - postgres
        - mastodon_auth_contract
        - tag_atom_feed_renderer
    - name: pleroma
      cases:
        - mastodon_controller
        - misskey_controller
        - dolphin_controller
        - meisskey_controller
        - mongo
        - misskey_auth_contract
        - tag_atom_feed_renderer
    - name: dropbox
      cases:
        - dropbox_clipper
        - dropbox_bookmark_handler
        - dropbox_clipping_command_handler
    - name: growi
      cases:
        - growi_clipper
        - growi_bookmark_handler
        - growi_clipping_command_handler
    - name: webhook
      cases:
        - webhook
        - webhook_image_handler
webui:
  scripts:
    - https://cdn.jsdelivr.net/npm/vue/dist/vue.js
    - https://cdn.jsdelivr.net/npm/vue-select/dist/vue-select.min.js
    - https://cdn.jsdelivr.net/npm/vuejs-dialog/dist/vuejs-dialog.min.js
    - https://cdn.jsdelivr.net/npm/v-tooltip/dist/v-tooltip.min.js
    - https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js
    - https://cdn.jsdelivr.net/npm/js-yaml/dist/js-yaml.min.js
  stylesheets:
    - /mulukhiya/style/default
    - https://cdn.jsdelivr.net/npm/vue-select/dist/vue-select.css
    - https://cdn.jsdelivr.net/npm/vuejs-dialog/dist/vuejs-dialog.min.css
    - https://use.fontawesome.com/releases/v5.6.1/css/all.css
    - https://fonts.googleapis.com/css?family=Francois+One|Inconsolata&display=swap
  metadata:
    robots: noindex,nofollow
    viewport: width=800
  livecure: false
mastodon:
  url: https://mstdn.example.com/
  dbms: postgres
  parser: toot
  handlers:
    pre_toot:
      - user_config_command
      - filter_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - itunes_image
      - spotify_image
      - amazon_image
      - you_tube_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tweet
      - tagging
      - invalid_command
    post_toot:
      - user_config_command
      - filter_command
      - growi_clipping_command
      - dropbox_clipping_command
      - tweet
      - result_notification
    pre_webhook:
      - itunes_image
      - spotify_image
      - amazon_image
      - you_tube_image
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    pre_thumbnail:
      - image_format_convert
      - image_resize
    post_thumbnail:
      - result_notification
    post_fav:
      - result_notification
    post_boost:
      - result_notification
    post_search:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - pre_thumbnail
    - post_thumbnail
    - post_fav
    - post_boost
    - post_search
    - post_bookmark
  oauth:
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    scopes:
      - write:statuses
      - write:media
      - read:filters
      - write:filters
  status:
    field: status
    key: id
    label: トゥート
    max_length: 500
  attachment:
    key: media_ids
  poll:
    options:
      field: options
  search:
    limit: 40
misskey:
  url: https://misskey.example.com/
  dbms: postgres
  parser: note
  handlers:
    pre_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tweet
      - tagging
      - invalid_command
    post_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - tweet
      - result_notification
    pre_webhook:
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  oauth:
    permission:
      - write:notes
      - write:drive
      - read:drive
    callback_url: /mulukhiya/auth
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: text
    key: noteId
    label: ノート
    max_length: 500
  attachment:
    key: fileIds
  poll:
    options:
      field: choices
meisskey:
  url: https://meisskey.example.com/
  dbms: mongo
  parser: note
  handlers:
    pre_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tweet
      - tagging
      - invalid_command
    post_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - tweet
      - result_notification
    pre_webhook:
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  oauth:
    permission:
      - write:notes
      - write:drive
      - read:drive
    callback_url: /mulukhiya/auth
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: text
    key: noteId
    label: ノート
    max_length: 1000
  attachment:
    key: fileIds
  poll:
    options:
      field: choices
dolphin:
  url: https://dolphin.example.com/
  dbms: postgres
  parser: note
  handlers:
    pre_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
      - invalid_command
    post_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  events:
    - pre_toot
    - post_toot
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: text
    key: noteId
    label: ノート
    max_length: 500
  attachment:
    key: fileIds
  poll:
    options:
      field: choices
pleroma:
  url: https://pleroma.example.com/
  dbms: postgres
  parser: toot
  handlers:
    pre_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - mention_visibility
      - amazon_image
      - you_tube_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tweet
      - tagging
      - invalid_command
    post_toot:
      - user_config_command
      - growi_clipping_command
      - dropbox_clipping_command
      - tweet
      - result_notification
    pre_webhook:
      - amazon_image
      - you_tube_image
      - webhook_image
      - shortened_url
      - url_normalize
      - canonical_url
      - itunes_url
      - amazon_url
      - itunes_nowplaying
      - amazon_nowplaying
      - spotify_nowplaying
      - itunes_url_nowplaying
      - amazon_url_nowplaying
      - spotify_url_nowplaying
      - you_tube_url_nowplaying
      - tagging
    post_webhook:
      - result_notification
    pre_upload:
      - image_format_convert
      - audio_format_convert
      - video_format_convert
      - image_resize
    post_upload:
      - result_notification
    post_bookmark:
      - dropbox_bookmark
      - growi_bookmark
      - result_notification
  oauth:
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    scopes:
      - write:statuses
      - write:media
      - read:statuses
  events:
    - pre_toot
    - post_toot
    - pre_webhook
    - post_webhook
    - pre_upload
    - post_upload
    - post_bookmark
  status:
    field: status
    key: id
    label: ステータス
    max_length: 5000
  attachment:
    key: media_ids
  poll:
    options:
      field: options
amazon:
  marketplace: jp
  urls:
    jp: https://www.amazon.co.jp/
  retry_limit: 5
  cache:
    ttl: 86400
  resources:
    - Images.Primary.Small
    - Images.Primary.Medium
    - Images.Primary.Large
    - Images.Variants.Small
    - Images.Variants.Medium
    - Images.Variants.Large
    - ItemInfo.ByLineInfo
    - ItemInfo.ContentInfo
    - ItemInfo.ContentRating
    - ItemInfo.Classifications
    - ItemInfo.ExternalIds
    - ItemInfo.Features
    - ItemInfo.ManufactureInfo
    - ItemInfo.ProductInfo
    - ItemInfo.TechnicalInfo
    - ItemInfo.Title
    - ItemInfo.TradeInInfo
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
  affiliate: false
spotify:
  language: ja,en-US;q=0.9,en;q=0.8
  urls:
    track: https://open.spotify.com/
  patterns:
    - pattern: /track/([[:alnum:]]+)
      type: track
    - pattern: /album/([[:alnum:]]+)
      type: album
itunes:
  country: jp
  lang: ja_jp
  urls:
    search: https://itunes.apple.com/search
    lookup: https://itunes.apple.com/lookup
  patterns:
    - pattern: /album/.*?/?([[:digit:]]+)$
      shortenable: true
  hosts:
    - music.apple.com
    - itunes.apple.com
youtube:
  url: https://www.googleapis.com/
twitter:
  consumer:
  status:
    tags: []
    length:
      max: 140
      url: 12
twittodon:
  pattern: \n(\n\(?.*?via\.\s+[^)]*\)?)$
artist_parser:
  delimiters:
    - /
    - 、
  patterns:
    - pattern: ^[^():]+、
      delimited: true
    - pattern: '^(((歌|語り):)?.+\s*\(CV[.:]\s*.+\)、?){2,}$'
      delimited: true
    - pattern: '^(.+\s*\(.+\)、?){2,}$'
      delimited: true
    - pattern: '^((歌|語り):)?(.+)\s*\(CV[.:]\s*(.+)\)$'
      items:
        - drop: true
        - drop: true
        - split: true
        - strip: true
          split: true
          prefix: 'CV:'
    - pattern: '^歌:(.+)\s*コーラス:(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(コーラス:(.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: 'コーラス:'
    - pattern: '^(.+)\s*\(as\s*(.+)\)$'
      items:
        - strip: true
          prefix: 'CV:'
        - split: true
    - pattern: '^(.+)\s*\((.+)\)$'
      items:
        - split: true
        - strip: true
          split: true
    - pattern: '^(.+)\s*feat\.\s*(.+)$'
      items:
        - split: true
        - strip: true
          split: true
          prefix: feat.
user_config:
  redis:
    dsn: redis://localhost:6379/1
postgres:
  dsn: null
mongo:
  dsn: null
slack:
  hooks: []
sidekiq:
  redis:
    dsn: redis://localhost:6379/2
  auth:
    user: admin
    password: ''
  concurrency: 5
  schedule:
    program_update:
      cron: '0 1 1 * * *'
      class: Mulukhiya::ProgramUpdateWorker
    media_cleaning:
      cron: '0 2 1 * * *'
      class: Mulukhiya::MediaCleaningWorker
    tagging_dictionary_update:
      cron: '0 3 1 * * *'
      class: Mulukhiya::TaggingDictionaryUpdateWorker
    announcement:
      every: 2m
      class: Mulukhiya::AnnouncementWorker
    tag_feed_update:
      every: 5m
      class: Mulukhiya::TagFeedUpdateWorker
puma:
  port: 3008
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
tagging:
  word:
    minimum_length: 3
  attachment_tags:
    image: image
    video: video
    audio: audio
  dictionaries:
    - url: https://precure.ml/api/dic/v1/precure.json
      type: relative
    - url: https://precure.ml/api/dic/v1/singer.json
      type: relative
    - url: https://precure.ml/api/dic/v1/series.json
      type: relative
    - url: https://precure.ml/api/dic/v2/fairy.json
feed:
  tag:
    limit: 100
  test_usernames:
    - test
webhook:
  sample: |
    わたしが斬るのは、あなたじゃない！
    絶ち切るのは弱さ。切り拓くは未来。心を貫く勇気の刃。
    それがわたし。王女様からもらった名前、キュアソードよ！
agent:
  accts:
    - '@relayctl@hashtag-relay.dtp-mstdn.jp'
crypt:
  password: mulukhiya
  salt: mulukhiya
