package:
  version: 2.1.19
  url: https://github.com/pooza/mulukhiya-toot-proxy
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
handler:
  default:
    timeout: 10
shortened_url:
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
    - spoti.fi
    - apple.co
mastodon:
  patterns:
    - pattern: ^/web/statuses/([[:digit:]]+)
    - pattern: ^/@[[:word:]]+/([[:digit:]]+)
  max_length: 500
  hashtag:
    pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
amazon:
  country: jp
  urls:
    jp: https://www.amazon.co.jp/
  retry_limit: 5
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/video/detail/([[:alnum:]]+)
      shortenable: true
  affiliate: false
spotify:
  language: ja,en-US;q=0.9,en;q=0.8
  retry_limit: 5
  urls:
    track: https://open.spotify.com/
  patterns:
    - pattern: /track/([[:alnum:]]+)
twitter:
  patterns:
    tweet: ^/(.+?)/status/([[:digit:]]+)
itunes:
  country: jp
  lang: ja_jp
  urls:
    search: https://itunes.apple.com/search
    lookup: https://itunes.apple.com/lookup
  patterns:
    - pattern: /album/.*?/([[:digit:]]+)$
      shortenable: true
nowplaying:
  hashtag: false
  artist_parser:
    delimiters:
      - /
      - 、
    patterns:
      - pattern: ^[^():]+、
        delimited: true
      - pattern: '^(((歌|語り):)?.+\s*\(CV[.:]\s*.+\)、?){2,}$'
        delimited: true
      - pattern: '^(.+\s*\(.+\)、?){2,}$'
        delimited: true
      - pattern: '^((歌|語り):)?(.+)\s*\(CV[.:]\s*(.+)\)$'
        items:
          - drop: true
          - drop: true
          - split: true
          - strip: true
            split: true
            prefix: 'CV:'
      - pattern: '^歌:(.+)\s*コーラス:(.+)$'
        items:
          - split: true
          - strip: true
            split: true
            prefix: 'コーラス:'
      - pattern: '^(.+)\s*\(コーラス:(.+)\)$'
        items:
          - split: true
          - strip: true
            split: true
            prefix: 'コーラス:'
      - pattern: '^(.+)\s*\(as\s*(.+)\)$'
        items:
          - strip: true
            prefix: 'CV:'
          - split: true
      - pattern: '^(.+)\s*\((.+)\)$'
        items:
          - split: true
          - strip: true
            split: true
      - pattern: '^(.+)\s*feat\.\s*(.+)$'
        items:
          - split: true
          - strip: true
            split: true
            prefix: feat.
redis:
  dsn: redis://localhost:6379/1
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
slack:
  hooks: []
sidekiq:
  redis:
    dsn: redis://localhost:6379/2
  auth:
    user: admin
    password: ''
tagging:
  word:
    minimum_length: 4
webhook:
  salt: mulukhiya
