package:
  version: 1.2.6
  url: https://github.com/pooza/mulukhiya-toot-proxy
shortened_url:
  timeout: 5
  domains:
    - t.co
    - goo.gl
    - bit.ly
    - ow.ly
    - amzn.to
    - amzn.asia
    - youtu.be
    - git.io
amazon_uri:
  patterns:
    - pattern: /dp/([[:alnum:]]+)
      shortenable: true
    - pattern: /gp/product/([[:alnum:]]+)
      shortenable: true
    - pattern: /exec/obidos/ASIN/([[:alnum:]]+)
      shortenable: true
    - pattern: /o/ASIN/([[:alnum:]]+)
      shortenable: true
amazon_ecs:
  retry_limit: 5
