inflections:
  amazon_uri: AmazonURI
  amazon_url_handler: AmazonURLHandler
  amazon_url_nowplaying_handler: AmazonURLNowplayingHandler
  canonical_url_handler: CanonicalURLHandler
  ci_test_case_filter: CITestCaseFilter
  css_renderer: CSSRenderer
  http: HTTP
  itunes_uri: ItunesURI
  itunes_url_handler: ItunesURLHandler
  itunes_url_nowplaying_handler: ItunesURLNowplayingHandler
  mime_type: MIMEType
  mongo_dsn: MongoDSN
  note_uri: NoteURI
  shortened_url_handler: ShortenedURLHandler
  spotify_uri: SpotifyURI
  spotify_url_nowplaying_handler: SpotifyURLNowplayingHandler
  toot_uri: TootURI
  uri: URI
  url_handler: URLHandler
  url_normalize_handler: URLNormalizeHandler
  video_uri: VideoURI
  you_tube_url_nowplaying_handler: YouTubeURLNowplayingHandler
