inflections:
  amazon_uri: AmazonURI
  amazon_url_handler: AmazonURLHandler
  canonical_url_handler: CanonicalURLHandler
  css_renderer: CSSRenderer
  html_renderer: HTMLRenderer
  http: HTTP
  itunes_uri: ItunesURI
  itunes_url_handler: ItunesURLHandler
  itunes_url_nowplaying_handler: ItunesURLNowplayingHandler
  note_uri: NoteURI
  shortened_url_handler: ShortenedURLHandler
  spotify_uri: SpotifyURI
  spotify_url_nowplaying_handler: SpotifyURLNowplayingHandler
  toot_uri: TootURI
  uri: URI
  url_handler: URLHandler
  url_normalize_handler: URLNormalizeHandler
  video_uri: VideoURI
  you_tube_url_nowplaying_handler: YouTubeURLNowplayingHandler
dirs:
  - contract
  - controller
  - daemon
  - file
  - handler
  - model
  - renderer
  - service
  - tagging_resource
  - test_case_filter
  - uri
  - worker
