- 2_6_9: /instance_url
  3_0_0: /mastodon/url
- 2_6_9: /nowplaying/artist_parser
  3_0_0: /artist_parser
- 2_6_9: /redis/dsn
  3_0_0: /user_config/redis/dsn
- 3_0_0: /mastodon/max_length
  3_1_0: /mastodon/toot/max_length
- 3_1_1: /handler/pre_toot
  3_2_0: /handler/mastodon/pre_toot
- 3_1_1: /handler/post_toot
  3_2_0: /handler/mastodon/post_toot
- 3_1_1: /handler/pre_webhook
  3_2_0: /handler/mastodon/pre_webhook
- 3_1_1: /handler/post_webhook
  3_2_0: /handler/mastodon/post_webhook
- 3_1_1: /handler/pre_upload
  3_2_0: /handler/mastodon/pre_upload
- 3_1_1: /handler/post_upload
  3_2_0: /handler/mastodon/post_upload
- 3_1_1: /handler/post_fav
  3_2_0: /handler/mastodon/post_fav
- 3_1_1: /handler/post_boost
  3_2_0: /handler/mastodon/post_boost
- 3_1_1: /handler/post_search
  3_2_0: /handler/mastodon/post_search
- 3_3_5: /mastodon/patterns
  3_4_0: /mastodon/toot/patterns
- 3_3_5: /dolphin/patterns
  3_4_0: /dolphin/note/patterns
- 3_3_5: /handler/mastodon
  3_4_0: /mastodon/handlers
- 3_3_5: /handler/dolphin
  3_4_0: /dolphin/handlers