token_owner: >-
  SELECT
  accounts.id,
  accounts.username,
  accounts.display_name
  FROM oauth_access_tokens AS tokens
  LEFT JOIN accounts ON tokens.resource_owner_id=accounts.id
  WHERE (tokens.token='<%= params[:token] %>');
