site: >-
  SELECT
  var,
  value
  FROM settings
  WHERE (var IN ('site_title','site_description','site_contact_username'))
  AND (thing_type IS NULL);
token_owner: >-
  SELECT
  resource_owner_id
  FROM oauth_access_token
  WHERE (token='<%= params[:token] %>');
