tagging:
  dictionaries:
    - url: https://script.googleusercontent.com/macros/echo?user_content_key=wo8gOi5Sh-9Jj2E6tEcH63gLpP1DfYNtSmg-krsg7mLQ5Yge-Zm0bUPp__23t1kqKPZk-Nq6mz4pY7JyzhNVLUasuCvtOx93m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnJPtSF1KzUJXTo_pA3Qll7V-53MZArfz9tlhkG4eAFvRdOPYcy3-_RURs1zUK59_LTGAbNhJnlep&lib=Mz_kSmMa676sbphxvXhpTCnGac_s0g0mR
      fields:
        - cure_name
        - human_name
        - cv
    - url: https://rubicure.herokuapp.com/series.json
      fields:
        - title
