version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repos
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install
      - run:
          name: run RuboCop
          command: |
            rubocop
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
