name: test

on:
  push:

env:
  CI: "true"
  RUBYOPT: -EUTF-8

jobs:
  test:
    runs-on: ubuntu-latest

    container: ${{ matrix.ruby }}

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - ruby:2.6
          - ruby:2.7

    steps:
      - uses: actions/checkout@v2

      - name: install ffmpeg
        run: |
          #udo apt install software-properties-common
          #sudo add-apt-repository ppa:mc3man/trusty-media
          #sudo apt update
          sudo apt install ffmpeg

      - name: install gems
        run: |
          gem install bundler
          bundle install
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: check gems
        run: |
          bundle exec rake bundle:update
          bundle exec rake bundle:check

      - name: Run lint
        run: |
          bundle exec rubocop
          bundle exec rake erb:check

      - name: Run test
        run: |
          bundle exec rake test
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
