name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: install ffmpeg
        run: |
          sudo add-apt-repository ppa:mc3man/trusty-media
          sudo apt update
          sudo apt install ffmpeg
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: check gems
        run: |
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - name: Run lint
        run: |
          bundle exec rubocop
          bundle exec rake erb:check
      - name: Run test
        run: |
          bundle exec rake test
